
try:
    print('Running the try...')
    print('5'+5)

# In 2.7 it's except Exception, e:

except Exception as e:
    print(str(e))
    print('Do more things...')

print('Code continues onwards')
